// tiposArchivos.ts
export const tiposArchivos: string[] = [
    "Mantenimiento Avianca",
    "Trafico Avianca",
    "Tierra Avianca",
    "Equipaje Avianca",
    "Analistas Avianca",
    "Total DELTA",
    "Total KLM",
    "Total LCP",
    "Total Quality Products",
    "Tierra LATAM",
    "Total REP",
    "Total AMERICAN",
    "Total TERPEL",
    "Total DHL",
    "Total INDECOPI",
    "AMERICAN TIERRA",
    "REP SI",
    "Total COPA AIR",
    "PLUSPETROL",
    "PLUSPETROL-PISCO",
    "PROSEGUR",
    "TALMA",
    "OI PERU",
    "CHINALCO",
    "METSO",
    "MOVILBUS",
    "OI LURIN",
    "METSO SSGG",
    "Total TERPEL AVIACION",
    "Total TERPEL COMERCIAL",
    "ATSA",
  ];

  export const empresa: string[] = [
    "AVIANCA",
    "LCP",
    "DELTA",
    "KLM",
    "REP SI",
    "LATAM",
    "REP",
    "AMERICAN",
    "TERPEL",
    "DHL",
    "INDECOPI",
    "AMERICAN TIERRA",
    "MOVILBUS",
    "COPA AIR",
    "PLUSPETROL",
    "PLUSPETROL-PISCO",
    "PROSEGUR",
    "TALMA",
    "OI PERU",
    "CHINALCO",
    "METSO",
    "OI LURIN",
    "METSO SSGG",
    "TERPEL AVIACION",
    "TERPEL COMERCIAL",
    "ATSA"
  ];
  
  