// tiposArchivos.ts
export const tiposArchivos: string[] = [
    "Mantenimiento Avianca",
    "Trafico Avianca",
    "Tierra Avianca",
    "Equipaje Avianca",
    "Analistas Avianca",
    "Total DELTA",
    "Total KLM",
    "Total LCP",
    "Total Quality Products",
    "Tierra LATAM",
    "Total REP",
    "Total AMERICAN",
    "Total TERPEL",
    "Total DHL",
    "Total INDECOPI",
    "AMERICAN TIERRA",
    "Total COPA AIR",
    "PLUSPETROL",
    "PLUSPETROL-PISCO",
    "PROSEGUR",
    "TALMA",
    "OI PERU",
    "CHINALCO",
    "METSO",
    "MOVILBUS",
    "OI LURIN",
    "METSO SSGG",
    "Total TERPEL AVIACION",
    "Total TERPEL COMERCIAL",
    "ATSA",
  ];
  